### PR TITLE
Select date view

### PR DESCRIPTION
**Pull request by TontonBuck**

### CODE REVIEW

**Comment by Aquaj** [comment]
What is this PR about?
The title says "Select date" but the code mentions:
- Date selectors
- The Apollo framework
- The lexicon
- Some work around phytosanitary products

PRs (and to an even more acute extent — commits) should be treated like classes and objects in code and follow [SRP (**S**ingle **R**esponsibility **P**rinciple)](https://en.wikipedia.org/wiki/Single_responsibility_principle): they should have *only one thing they're doing* and be named properly to show exactly what that is.

**Comment by TontonBuck** [comment]
I thought I created another branch before but it's only when I pushed that I saw the branch wasn't created. I will look to remove last commits

**Comment by Aquaj** [comment]
You probably won't be able to "remove" the commits without a force-push. If it comes to that, I'd rather you open a new PR and/or create a new branch as needed instead of `git push --force`.

Check out k88hudson/git-flight-rules it might help you out.

**Comment by TontonBuck** [comment]
I didn't see your comment and force-pushed removing last 5 commits. New branch called inputs-lexicon has these 5 commits

**Comment by Aquaj** [comment]
Alright. Too bad but could be worse, I'll check that out.

**Pull request merged**
